version: '3'

services:
  # The load balancer
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    
  apiClientes:
    build: ./api_clientes
    container_name: api_clientes
    image: api_clientes