version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb_backend_develop
    environment: 
      - MONGO_DATA_DIR=/data/db:ro
      - MONGO_LOG_DIR=/var/log/mongodb
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - 27015:27017
    networks: 
      - back_end
  api:
    build: .
    ports:
      - 4001:4000
    depends_on:
      - db
    environment:
      - API_CLIENTES_URL=http://api_clientes_api_1:4000
      - API_PRODUCTOS_URL=https://productos.free.beeceptor.com
      - DB_NAME=${MONGO_INITDB_DATABASE}
      - DB_HOST=mongodb_backend_develop
      - DB_PORT=27017
      - DB_USERNAME=${MONGO_INITDB_USERNAME}
      - DB_PASSWORD=${MONGO_INITDB_PASSWORD}
      - DB_AUTH=${MONGO_AUTHDB}
      - PORT=4000
    networks:
      - back_end
      
networks: 
  back_end:
    external: true