version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb_backend_develop
    environment: 
      - MONGO_DATA_DIR=/data/db:ro
      - MONGO_LOG_DIR=/var/log/mongodb
      - MONGO_INITDB_ROOT_USERNAME=pedidos
      - MONGO_INITDB_ROOT_PASSWORD=pedidos
      - MONGO_INITDB_DATABASE=pedidos
    ports:
      - 27015:27017
    networks: 
      - back_end
  api:
    build: .
    container_name: api_pedidos_dev
    ports:
      - 4001:4000
    depends_on:
      - db
    environment:
      - API_CLIENTES_URL=api_clientes:4000
      - DB_NAME=pedidos
      - DB_HOST=mongodb_backend_develop
      - DB_PORT=27017
      - DB_USERNAME=pedidos
      - DB_PASSWORD=pedidos
      - DB_AUTH=admin
    networks:
      - back_end
      
networks: 
  back_end:
    external: true